version: '3'

dotenv: ['.env']

vars:
  CURRENT_DIR:
    sh: pwd

tasks:
  build:
    cmds:
      - docker build -t jdudmesh/country-labeler .

  run:
    cmds:
      - docker run -it jdudmesh/country-labeler

  push:
    cmds:
      - docker push jdudmesh/country-labeler
